import type { NextPage } from "next";
import Head from "next/head";
import { useGamesPlaytimeQuery, useGamesQuery } from "../graphql";

const Home: NextPage = () => {
  const { loading, error, data } = useGamesQuery({ variables: { limit: 5 } });
  const games2 = useGamesPlaytimeQuery();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <div>
          <>
            {data?.games?.map((game) => (
              <p key={game.id}>{game.name}</p>
            ))}
          </>
        </div>
        <div>
          <>
            {games2.data?.games?.map((game) => (
              <p key={game.id}>{game.playtime}</p>
            ))}
          </>
        </div>
      </main>
    </div>
  );
};

export default Home;
